version: '3.8'

x-postgres-variables: &postgres-variables
#  POSTGRES_DB: "${DB__NAME}"
#  POSTGRES_USER: "${DB__USER}"
#  POSTGRES_PASSWORD: "${DB__PASSWORD}"
  POSTGRES_DB: "${DB__NAME:-postgres}"
  POSTGRES_USER: "${DB__USER:-postgres}"
  POSTGRES_PASSWORD: "${DB__PASSWORD:-postgres}"

services:
  web:
    container_name: fastapi-template-web
    build: .
    command: uvicorn apps.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    env_file:
      - infra/envs/.env
    environment:
      - DB__HOST=db
      - DB__PORT=5432
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: fastapi-template-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      <<: *postgres-variables
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB__USER:-postgres} -d ${DB__NAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
