version: '3.9'

x-common: &common
  image:  ${IMAGE_TAG}
  secrets:
    - postgres_password
  env_file:
    - ../../envs/.env.test
  networks:
    -project-net

services:
  web:
    <<: *common
    command:
      - uvicorn app.main:app --host 0.0.0.0 --port 8001 --workers 2 --log-level debug
    ports:
      - "8001:8001"
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthcheck"]
      interval: 5s
      retries: 4
    deploy:
      replicas: 2

networks:
  project-net:
    external: true

secrets:
  postgres_password:
    external: true