"""add cascade delete to habit instances

Revision ID: 38d5ee9ef9c1
Revises: 428854d51e3c
Create Date: 2025-06-17 09:11:59.038849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d5ee9ef9c1'
down_revision: Union[str, None] = '428854d51e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('habitinstances_habit_id_fkey', 'habitinstances', type_='foreignkey')
    op.create_foreign_key(None, 'habitinstances', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habitinstances', type_='foreignkey')
    op.create_foreign_key('habitinstances_habit_id_fkey', 'habitinstances', 'habits', ['habit_id'], ['id'])
    # ### end Alembic commands ###
